openapi: 3.0.0
info:
  title: Expense Tracker
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: local development version
paths: 
  /records:
    get:
      summary: get all records with filters
      parameters: 
        - in: query
          name: month 
          description: YYYY-MM
          schema:
            type: string
        - in: query
          name: utcOffset
          description: "timezone, e.g.: +8, -8"
          schema:
            type: string
          example: '+8'
        - in: query
          name: search
          description: keywords of record name
          schema:
            type: string
        - in: query
          name: sort
          description: '[field name]-[desc or asc]'
          schema:
            type: string
          example: name-desc
        - in: query
          name: categoryId
          schema:
            type: integer
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    $ref: '#/components/schemas/Records'
                  totalAmount:
                    type: number
        404:
          $ref: '#/components/responses/NoRecords'
          
components:
  responses:
    NoRecords:
      description: No records found. Please check your filtering conditions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            message: No records found. Please check your filtering conditions.
  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: <specific error message>
          
    Records:
      type: array
      items:
        $ref: '#/components/schemas/Record'
    Record:
      type: object
      properties:
        _id: 
          type: string
          example: 5ffae7915e002e626c1e42f9
        name:
          type: string
          example: rent
        category:
          $ref: '#/components/schemas/Category'
        date:
          type: string
          format: date-time
        amount: 
          type: number
          format: float
          example: 1200
        merchant:
          type: string
          example: house
        userId:
          type: string
          example: 5ff828391a098c4a8cadcba0
    Category: 
      type: object
      properties:
        _id: 
          type: string
          example: 5ff828381a098c4a8cadcb9a
        name:
          type: string
          example: housing
        iconClass:
          type: string
          description: font awesome icon class
          example: fas fa-home