openapi: 3.0.0
info:
  title: Expense Tracker
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: local development version
paths: 
  /records:
    get:
      summery: get all records with filters
      parameters: 
        - in: query
          name: month 
          description: YYYY-MM
          schema:
            type: string
        - in: query
          name: utcOffset
          description: "timezone, e.g.: +8, -8"
          schema:
            type: string
          example: '+8'
        - in: query
          name: search
          description: keywords of record name
          schema:
            type: string
        - in: query
          name: sort
          description: '[field name]-[desc or asc]'
          schema:
            type: string
          example: name-desc
        - in: query
          name: categoryId
          schema:
            type: integer
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    schema:
                      $ref: '#/components/schemas/Records'
                  totalAmount:
                    type: number
components:
  schemas:
    Records:
      type: array
      items:
        schema:
          $ref: '#/components/schemas/Record'
    Record:
      type: object
      properties:
        id: 
          type: integer
        name:
          type: string
        category:
          type: object
        date:
          type: string
          format: date-time
        amount: 
          type: number
        merchant:
          type: string
        userId:
          type: integer




